function [Val varNames]=readref(filename)
%function to read the R- and GOF-values from JANA .ref-file
str = fileread(filename);

varStr={'\|R\(obs\)=' ...
    'wR\(obs\)=' ...
    'R\(all\)=' ...
    'wR\(all\)=' ...
    'GOF\(obs\)=' ...
    'GOF\(all\)='};

varNames={'R(obs)' ...
    'R(obs)' ...
    'R(all)' ...
    'wR(all)' ...
    'GOF(obs)' ...
    'GOF(all)'};

Val=zeros(length(varStr),1);
for k=1:length(varStr)
    T = regexp(str, ['(?-s)(?m)' varStr{k} '\s*(\S+)'], 'tokens');
    Val(k)=str2double(T{1});
end

end